# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64'
gem 'httparty'
gem 'nats-pure', '~> 2.4.0'
gem 'pry'
gem 'rubocop'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'webmock', '~> 3.18'
end
